name: Core Build & Test (All Branches)

on:
  pull_request:
    branches: [main]
    # No branch filtering - safety net for all PRs

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Cache .NET packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/GanttComponents
        
      - name: Build application
        run: dotnet build --no-restore --configuration Release
        working-directory: ./src/GanttComponents
        
      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./tests/GanttComponents.Tests
        
      - name: Check compilation status
        run: |
          echo "✅ Core build and test validation completed successfully"
          echo "   - Solution compiles without errors"
          echo "   - Unit tests pass"
          echo "   - Ready for specialized validation based on branch type"
